// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_ZFdp_kSHC1UHHEe1ZRvK548ELK7dS9c',
    appId: '1:367161320199:web:6fc8f63dd423f05f8b9ba2',
    messagingSenderId: '367161320199',
    projectId: 'cocktail-41acc',
    authDomain: 'cocktail-41acc.firebaseapp.com',
    storageBucket: 'cocktail-41acc.appspot.com',
    measurementId: 'G-RKN3QW0M0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQNKcNRdsgfMKJJlyILlbx0PQQSSdf3bs',
    appId: '1:367161320199:android:5c4f76dc5c13c0e98b9ba2',
    messagingSenderId: '367161320199',
    projectId: 'cocktail-41acc',
    storageBucket: 'cocktail-41acc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSEsMV9GrLLTcsUl57cVw1XpIrAWZ2rpU',
    appId: '1:367161320199:ios:d8523ad029139d0e8b9ba2',
    messagingSenderId: '367161320199',
    projectId: 'cocktail-41acc',
    storageBucket: 'cocktail-41acc.appspot.com',
    iosBundleId: 'com.example.cocktailApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSEsMV9GrLLTcsUl57cVw1XpIrAWZ2rpU',
    appId: '1:367161320199:ios:90941332ca6d4bc28b9ba2',
    messagingSenderId: '367161320199',
    projectId: 'cocktail-41acc',
    storageBucket: 'cocktail-41acc.appspot.com',
    iosBundleId: 'com.example.cocktailApp.RunnerTests',
  );
}
